import { RealmOption, RegionOption } from "../types/types";

export const REGIONS: RegionOption[] = [
  {
    label: "US",
    value: "us",
    flagPath: "/USFlag.svg",
  },
  {
    label: "EU",
    value: "eu",
    flagPath: "/EUFlag.svg",
  },
  {
    label: "KR",
    value: "kr",
    flagPath: "/KRFlag.svg",
  },
  {
    label: "TW",
    value: "tw",
    flagPath: "/TWFlag.svg",
  },
];

export const US_REALMS: RealmOption[] = [
  { label: "Aegwynn", value: "aegwynn" },
  { label: "Aerie Peak", value: "aerie-peak" },
  { label: "Agamaggan", value: "agamaggan" },
  { label: "Aggramar", value: "aggramar" },
  { label: "Akama", value: "akama" },
  { label: "Alexstrasza", value: "alexstrasza" },
  { label: "Alleria", value: "alleria" },
  { label: "Altar of Storms", value: "altar-of-storms" },
  { label: "Alterac Mountains", value: "alterac-mountains" },
  { label: "Andorhal", value: "andorhal" },
  { label: "Anetheron", value: "anetheron" },
  { label: "Antonidas", value: "antonidas" },
  { label: "Anub'arak", value: "anubarak" },
  { label: "Anvilmar", value: "anvilmar" },
  { label: "Arathor", value: "arathor" },
  { label: "Archimonde", value: "archimonde" },
  { label: "Area 52", value: "area-52" },
  { label: "Argent Dawn", value: "argent-dawn" },
  { label: "Arthas", value: "arthas" },
  { label: "Arygos", value: "arygos" },
  { label: "Auchindoun", value: "auchindoun" },
  { label: "Azgalor", value: "azgalor" },
  { label: "Azjol-Nerub", value: "azjol-nerub" },
  { label: "Azralon", value: "azralon" },
  { label: "Azshara", value: "azshara" },
  { label: "Azuremyst", value: "azuremyst" },
  { label: "Baelgun", value: "baelgun" },
  { label: "Balnazzar", value: "balnazzar" },
  { label: "Black Dragonflight", value: "black-dragonflight" },
  { label: "Blackhand", value: "blackhand" },
  { label: "Blackrock", value: "blackrock" },
  { label: "Blackwater Raiders", value: "blackwater-raiders" },
  { label: "Blackwing Lair", value: "blackwing-lair" },
  { label: "Blade's Edge", value: "blades-edge" },
  { label: "Bladefist", value: "bladefist" },
  { label: "Bleeding Hollow", value: "bleeding-hollow" },
  { label: "Blood Furnace", value: "blood-furnace" },
  { label: "Bloodhoof", value: "bloodhoof" },
  { label: "Bloodscalp", value: "bloodscalp" },
  { label: "Bonechewer", value: "bonechewer" },
  { label: "Borean Tundra", value: "borean-tundra" },
  { label: "Boulderfist", value: "boulderfist" },
  { label: "Bronzebeard", value: "bronzebeard" },
  { label: "Burning Blade", value: "burning-blade" },
  { label: "Burning Legion", value: "burning-legion" },
  { label: "Cairne", value: "cairne" },
  { label: "Cenarion Circle", value: "cenarion-circle" },
  { label: "Cenarius", value: "cenarius" },
  { label: "Cho'gall", value: "chogall" },
  { label: "Chromaggus", value: "chromaggus" },
  { label: "Coilfang", value: "coilfang" },
  { label: "Crushridge", value: "crushridge" },
  { label: "Daggerspine", value: "daggerspine" },
  { label: "Dalaran", value: "dalaran" },
  { label: "Dalvengyr", value: "dalvengyr" },
  { label: "Dark Iron", value: "dark-iron" },
  { label: "Darkspear", value: "darkspear" },
  { label: "Darrowmere", value: "darrowmere" },
  { label: "Dawnbringer", value: "dawnbringer" },
  { label: "Deathwing", value: "deathwing" },
  { label: "Demon Soul", value: "demon-soul" },
  { label: "Dentarg", value: "dentarg" },
  { label: "Destromath", value: "destromath" },
  { label: "Dethecus", value: "dethecus" },
  { label: "Detheroc", value: "detheroc" },
  { label: "Doomhammer", value: "doomhammer" },
  { label: "Draenor", value: "draenor" },
  { label: "Dragonblight", value: "dragonblight" },
  { label: "Dragonmaw", value: "dragonmaw" },
  { label: "Drak'Tharon", value: "draktharon" },
  { label: "Drak'thul", value: "drakthul" },
  { label: "Draka", value: "draka" },
  { label: "Drakkari", value: "drakkari" },
  { label: "Drenden", value: "drenden" },
  { label: "Dunemaul", value: "dunemaul" },
  { label: "Durotan", value: "durotan" },
  { label: "Duskwood", value: "duskwood" },
  { label: "Earthen Ring", value: "earthen-ring" },
  { label: "Echo Isles", value: "echo-isles" },
  { label: "Eitrigg", value: "eitrigg" },
  { label: "Eldre'Thalas", value: "eldrethalas" },
  { label: "Elune", value: "elune" },
  { label: "Emerald Dream", value: "emerald-dream" },
  { label: "Eonar", value: "eonar" },
  { label: "Eredar", value: "eredar" },
  { label: "Executus", value: "executus" },
  { label: "Exodar", value: "exodar" },
  { label: "Farstriders", value: "farstriders" },
  { label: "Feathermoon", value: "feathermoon" },
  { label: "Fenris", value: "fenris" },
  { label: "Firetree", value: "firetree" },
  { label: "Fizzcrank", value: "fizzcrank" },
  { label: "Frostmane", value: "frostmane" },
  { label: "Frostwolf", value: "frostwolf" },
  { label: "Galakrond", value: "galakrond" },
  { label: "Gallywix", value: "gallywix" },
  { label: "Garithos", value: "garithos" },
  { label: "Garona", value: "garona" },
  { label: "Garrosh", value: "garrosh" },
  { label: "Ghostlands", value: "ghostlands" },
  { label: "Gilneas", value: "gilneas" },
  { label: "Gnomeregan", value: "gnomeregan" },
  { label: "Gorefiend", value: "gorefiend" },
  { label: "Gorgonnash", value: "gorgonnash" },
  { label: "Greymane", value: "greymane" },
  { label: "Grizzly Hills", value: "grizzly-hills" },
  { label: "Gul'dan", value: "guldan" },
  { label: "Gurubashi", value: "gurubashi" },
  { label: "Hakkar", value: "hakkar" },
  { label: "Haomarush", value: "haomarush" },
  { label: "Hellscream", value: "hellscream" },
  { label: "Hydraxis", value: "hydraxis" },
  { label: "Hyjal", value: "hyjal" },
  { label: "Icecrown", value: "icecrown" },
  { label: "Illidan", value: "illidan" },
  { label: "Jaedenar", value: "jaedenar" },
  { label: "Kael'thas", value: "kaelthas" },
  { label: "Kalecgos", value: "kalecgos" },
  { label: "Kargath", value: "kargath" },
  { label: "Kel'Thuzad", value: "kelthuzad" },
  { label: "Khadgar", value: "khadgar" },
  { label: "Khaz Modan", value: "khaz-modan" },
  { label: "Kil'jaeden", value: "kiljaeden" },
  { label: "Kilrogg", value: "kilrogg" },
  { label: "Kirin Tor", value: "kirin-tor" },
  { label: "Korgath", value: "korgath" },
  { label: "Korialstrasz", value: "korialstrasz" },
  { label: "Kul Tiras", value: "kul-tiras" },
  { label: "Laughing Skull", value: "laughing-skull" },
  { label: "Lethon", value: "lethon" },
  { label: "Lightbringer", value: "lightbringer" },
  { label: "Lightning's Blade", value: "lightnings-blade" },
  { label: "Llane", value: "llane" },
  { label: "Lothar", value: "lothar" },
  { label: "Madoran", value: "madoran" },
  { label: "Maelstrom", value: "maelstrom" },
  { label: "Magtheridon", value: "magtheridon" },
  { label: "Maiev", value: "maiev" },
  { label: "Mal'Ganis", value: "malganis" },
  { label: "Malfurion", value: "malfurion" },
  { label: "Malorne", value: "malorne" },
  { label: "Malygos", value: "malygos" },
  { label: "Mannoroth", value: "mannoroth" },
  { label: "Medivh", value: "medivh" },
  { label: "Misha", value: "misha" },
  { label: "Mok'Nathal", value: "moknathal" },
  { label: "Moon Guard", value: "moon-guard" },
  { label: "Moonrunner", value: "moonrunner" },
  { label: "Mug'thol", value: "mugthol" },
  { label: "Muradin", value: "muradin" },
  { label: "Nagrand", value: "nagrand" },
  { label: "Nathrezim", value: "nathrezim" },
  { label: "Nazgrel", value: "nazgrel" },
  { label: "Nazjatar", value: "nazjatar" },
  { label: "Nemesis", value: "nemesis" },
  { label: "Ner'zhul", value: "nerzhul" },
  { label: "Nesingwary", value: "nesingwary" },
  { label: "Nordrassil", value: "nordrassil" },
  { label: "Norgannon", value: "norgannon" },
  { label: "Onyxia", value: "onyxia" },
  { label: "Perenolde", value: "perenolde" },
  { label: "Proudmoore", value: "proudmoore" },
  { label: "Quel'dorei", value: "queldorei" },
  { label: "Ravencrest", value: "ravencrest" },
  { label: "Ravenholdt", value: "ravenholdt" },
  { label: "Rexxar", value: "rexxar" },
  { label: "Rivendare", value: "rivendare" },
  { label: "Runetotem", value: "runetotem" },
  { label: "Sargeras", value: "sargeras" },
  { label: "Saurfang", value: "saurfang" },
  { label: "Scarlet Crusade", value: "scarlet-crusade" },
  { label: "Scilla", value: "scilla" },
  { label: "Sen'jin", value: "senjin" },
  { label: "Sentinels", value: "sentinels" },
  { label: "Shadow Council", value: "shadow-council" },
  { label: "Shadowmoon", value: "shadowmoon" },
  { label: "Shadowsong", value: "shadowsong" },
  { label: "Shandris", value: "shandris" },
  { label: "Shattered Halls", value: "shattered-halls" },
  { label: "Shattered Hand", value: "shattered-hand" },
  { label: "Shu'halo", value: "shuhalo" },
  { label: "Silver Hand", value: "silver-hand" },
  { label: "Silvermoon", value: "silvermoon" },
  { label: "Sisters of Elune", value: "sisters-of-elune" },
  { label: "Skullcrusher", value: "skullcrusher" },
  { label: "Skywall", value: "skywall" },
  { label: "Smolderthorn", value: "smolderthorn" },
  { label: "Spinebreaker", value: "spinebreaker" },
  { label: "Spirestone", value: "spirestone" },
  { label: "Staghelm", value: "staghelm" },
  { label: "Steamwheedle Cartel", value: "steamwheedle-cartel" },
  { label: "Stonemaul", value: "stonemaul" },
  { label: "Stormrage", value: "stormrage" },
  { label: "Stormreaver", value: "stormreaver" },
  { label: "Stormscale", value: "stormscale" },
  { label: "Suramar", value: "suramar" },
  { label: "Tanaris", value: "tanaris" },
  { label: "Terenas", value: "terenas" },
  { label: "Terokkar", value: "terokkar" },
  { label: "Thaurissan", value: "thaurissan" },
  { label: "The Forgotten Coast", value: "the-forgotten-coast" },
  { label: "The Scryers", value: "the-scryers" },
  { label: "The Underbog", value: "the-underbog" },
  { label: "The Venture Co", value: "the-venture-co" },
  { label: "Thorium Brotherhood", value: "thorium-brotherhood" },
  { label: "Thrall", value: "thrall" },
  { label: "Thunderhorn", value: "thunderhorn" },
  { label: "Thunderlord", value: "thunderlord" },
  { label: "Tichondrius", value: "tichondrius" },
  { label: "Tol Barad", value: "tol-barad" },
  { label: "Tortheldrin", value: "tortheldrin" },
  { label: "Trollbane", value: "trollbane" },
  { label: "Turalyon", value: "turalyon" },
  { label: "Twisting Nether", value: "twisting-nether" },
  { label: "Uldaman", value: "uldaman" },
  { label: "Uldum", value: "uldum" },
  { label: "Undermine", value: "undermine" },
  { label: "Ursin", value: "ursin" },
  { label: "Uther", value: "uther" },
  { label: "Vashj", value: "vashj" },
  { label: "Vek'nilash", value: "veknilash" },
  { label: "Velen", value: "velen" },
  { label: "Warsong", value: "warsong" },
  { label: "Whisperwind", value: "whisperwind" },
  { label: "Wildhammer", value: "wildhammer" },
  { label: "Windrunner", value: "windrunner" },
  { label: "Winterhoof", value: "winterhoof" },
  { label: "Ysera", value: "ysera" },
  { label: "Ysondre", value: "ysondre" },
  { label: "Zangarmarsh", value: "zangarmarsh" },
  { label: "Zul'jin", value: "zuljin" },
  { label: "Zuluhed", value: "zuluhed" },
];

export const EU_REALMS: RealmOption[] = [
  { label: "Aegwynn", value: "aegwynn" },
  { label: "Aerie Peak", value: "aerie-peak" },
  { label: "Agamaggan", value: "agamaggan" },
  { label: "Aggra (Português)", value: "aggra-portugues" },
  { label: "Aggramar", value: "aggramar" },
  { label: "Ahn'Qiraj", value: "ahn-qiraj" },
  { label: "Al'Akir", value: "al-akir" },
  { label: "Alexstrasza", value: "alexstrasza" },
  { label: "Alleria", value: "alleria" },
  { label: "Alonsus", value: "alonsus" },
  { label: "Aman'Thul", value: "aman-thul" },
  { label: "Ambossar", value: "ambossar" },
  { label: "Anachronos", value: "anachronos" },
  { label: "Anetheron", value: "anetheron" },
  { label: "Antonidas", value: "antonidas" },
  { label: "Anub'arak", value: "anub-arak" },
  { label: "Arak-arahm", value: "arak-arahm" },
  { label: "Arathi", value: "arathi" },
  { label: "Arathor", value: "arathor" },
  { label: "Archimonde", value: "archimonde" },
  { label: "Area 52", value: "area-52" },
  { label: "Argent Dawn", value: "argent-dawn" },
  { label: "Arthas", value: "arthas" },
  { label: "Arygos", value: "arygos" },
  { label: "Ashbringer", value: "ashbringer" },
  { label: "Aszune", value: "aszune" },
  { label: "Auchindoun", value: "auchindoun" },
  { label: "Azjol-Nerub", value: "azjol-nerub" },
  { label: "Azshara", value: "azshara" },
  { label: "Azuregos", value: "azuregos" },
  { label: "Azuremyst", value: "azuremyst" },
  { label: "Baelgun", value: "baelgun" },
  { label: "Balnazzar", value: "balnazzar" },
  { label: "Blackhand", value: "blackhand" },
  { label: "Blackmoore", value: "blackmoore" },
  { label: "Blackrock", value: "blackrock" },
  { label: "Bloodfeather", value: "bloodfeather" },
  { label: "Bloodhoof", value: "bloodhoof" },
  { label: "Bloodscalp", value: "bloodscalp" },
  { label: "Blutkessel", value: "blutkessel" },
  { label: "Booty Bay", value: "booty-bay" },
  { label: "Borean Tundra", value: "borean-tundra" },
  { label: "Boulderfist", value: "boulderfist" },
  { label: "Bronze Dragonflight", value: "bronze-dragonflight" },
  { label: "Bronzebeard", value: "bronzebeard" },
  { label: "Burning Blade", value: "burning-blade" },
  { label: "Burning Legion", value: "burning-legion" },
  { label: "Burning Steppes", value: "burning-steppes" },
  { label: "C'Thun", value: "c-thun" },
  { label: "Chamber of Aspects", value: "chamber-of-aspects" },
  { label: "Chants éternels", value: "chants-eternels" },
  { label: "Cho'gall", value: "cho-gall" },
  { label: "Chromaggus", value: "chromaggus" },
  { label: "Colinas Pardas", value: "colinas-pardas" },
  { label: "Confrérie du Thorium", value: "confrerie-du-thorium" },
  { label: "Conseil des Ombres", value: "conseil-des-ombres" },
  { label: "Crushridge", value: "crushridge" },
  { label: "Cult of the Forgotten", value: "cult-of-the-forgotten" },
  { label: "Daggerspine", value: "daggerspine" },
  { label: "Dalaran", value: "dalaran" },
  { label: "Dalvengyr", value: "dalvengyr" },
  { label: "Darkmoon Faire", value: "darkmoon-faire" },
  { label: "Darksorrow", value: "darksorrow" },
  { label: "Darkspear", value: "darkspear" },
  { label: "Das Konsortium", value: "das-konsortium" },
  { label: "Das Syndikat", value: "das-syndikat" },
  { label: "Deathguard", value: "deathguard" },
  { label: "Deathweaver", value: "deathweaver" },
  { label: "Deathwing", value: "deathwing" },
  { label: "Deepholm", value: "deepholm" },
  { label: "Defias Brotherhood", value: "defias-brotherhood" },
  { label: "Dentarg", value: "dentarg" },
  { label: "Der Abyssische Rat", value: "der-abyssische-rat" },
  { label: "Der Mithrilorden", value: "der-mithrilorden" },
  { label: "Der Rat von Dalaran", value: "der-rat-von-dalaran" },
  { label: "Destromath", value: "destromath" },
  { label: "Dethecus", value: "dethecus" },
  { label: "Die Aldor", value: "die-aldor" },
  { label: "Die Arguswacht", value: "die-arguswacht" },
  { label: "Die Nachtwache", value: "die-nachtwache" },
  { label: "Die Silberne Hand", value: "die-silberne-hand" },
  { label: "Die Todeskrallen", value: "die-todeskrallen" },
  { label: "Die ewige Wacht", value: "die-ewige-wacht" },
  { label: "Doomhammer", value: "doomhammer" },
  { label: "Draenor", value: "draenor" },
  { label: "Dragonblight", value: "dragonblight" },
  { label: "Dragonmaw", value: "dragonmaw" },
  { label: "Drak'thul", value: "drak-thul" },
  { label: "Drek'Thar", value: "drek-thar" },
  { label: "Dun Modr", value: "dun-modr" },
  { label: "Dun Morogh", value: "dun-morogh" },
  { label: "Dunemaul", value: "dunemaul" },
  { label: "Durotan", value: "durotan" },
  { label: "Earthen Ring", value: "earthen-ring" },
  { label: "Echsenkessel", value: "echsenkessel" },
  { label: "Eitrigg", value: "eitrigg" },
  { label: "Eldre'Thalas", value: "eldre-thalas" },
  { label: "Elune", value: "elune" },
  { label: "Emerald Dream", value: "emerald-dream" },
  { label: "Eonar", value: "eonar" },
  { label: "Eredar", value: "eredar" },
  { label: "Eversong", value: "eversong" },
  { label: "Executus", value: "executus" },
  { label: "Exodar", value: "exodar" },
  { label: "Festung der Stürme", value: "festung-der-sturme" },
  { label: "Fordragon", value: "fordragon" },
  { label: "Forscherliga", value: "forscherliga" },
  { label: "Frostmane", value: "frostmane" },
  { label: "Frostmourne", value: "frostmourne" },
  { label: "Frostwhisper", value: "frostwhisper" },
  { label: "Frostwolf", value: "frostwolf" },
  { label: "Galakrond", value: "galakrond" },
  { label: "Garona", value: "garona" },
  { label: "Garrosh", value: "garrosh" },
  { label: "Gilneas", value: "gilneas" },
  { label: "Gorgonnash", value: "gorgonnash" },
  { label: "Gul'dan", value: "guldan" },
  { label: "Kargath", value: "kargath" },
  { label: "Kel'Thuzad", value: "kelthuzad" },
  { label: "Khaz'goroth", value: "khazgoroth" },
  { label: "Kil'jaeden", value: "kiljaeden" },
  { label: "Krag'jin", value: "kragjin" },
  { label: "Kult der Verdammten", value: "kult-der-verdammten" },
  { label: "Lordaeron", value: "lordaeron" },
  { label: "Lothar", value: "lothar" },
  { label: "Madmortem", value: "madmortem" },
  { label: "Mal'Ganis", value: "malganis" },
  { label: "Malfurion", value: "malfurion" },
  { label: "Malorne", value: "malorne" },
  { label: "Malygos", value: "malygos" },
  { label: "Mannoroth", value: "mannoroth" },
  { label: "Mug'thol", value: "mugthol" },
  { label: "Nathrezim", value: "nathrezim" },
  { label: "Nazjatar", value: "nazjatar" },
  { label: "Nefarian", value: "nefarian" },
  { label: "Nera'thor", value: "nerathor" },
  { label: "Nethersturm", value: "nethersturm" },
  { label: "Norgannon", value: "norgannon" },
  { label: "Nozdormu", value: "nozdormu" },
  { label: "Onyxia", value: "onyxia" },
  { label: "Perenolde", value: "perenolde" },
  { label: "Proudmoore", value: "proudmoore" },
  { label: "Rajaxx", value: "rajaxx" },
  { label: "Rexxar", value: "rexxar" },
  { label: "Sen'jin", value: "senjin" },
  { label: "Shattrath", value: "shattrath" },
  { label: "Taerar", value: "taerar" },
  { label: "Teldrassil", value: "teldrassil" },
  { label: "Terrordar", value: "terrordar" },
  { label: "Theradras", value: "theradras" },
  { label: "Thrall", value: "thrall" },
  { label: "Tichondrius", value: "tichondrius" },
  { label: "Tirion", value: "tirion" },
  { label: "Todeswache", value: "todeswache" },
  { label: "Ulduar", value: "ulduar" },
  { label: "Un'Goro", value: "ungoro" },
  { label: "Vek'lor", value: "veklor" },
  { label: "Wrathbringer", value: "wrathbringer" },
  { label: "Ysera", value: "ysera" },
  { label: "Zirkel des Cenarius", value: "zirkel-des-cenarius" },
  { label: "Zuluhed", value: "zuluhed" },
];

export const KR_REALMS: RealmOption[] = [
  { label: "Alexstrasza", value: "alexstrasza" },
  { label: "Azshara", value: "azshara" },
  { label: "Burning Legion", value: "burning-legion" },
  { label: "Cenarius", value: "cenarius" },
  { label: "Dalaran", value: "dalaran" },
  { label: "Deathwing", value: "deathwing" },
  { label: "Durotan", value: "durotan" },
  { label: "Garona", value: "garona" },
  { label: "Gul'dan", value: "guldan" },
  { label: "Hellscream", value: "hellscream" },
  { label: "Hyjal", value: "hyjal" },
  { label: "Malfurion", value: "malfurion" },
  { label: "Norgannon", value: "norgannon" },
  { label: "Zul'jin", value: "zuljin" }
]

export const TW_REALMS: RealmOption[] = [
  { label: "Arthas", value: "arthas" },
  { label: "Arygos", value: "arygos" },
  { label: "Bleeding Hollow", value: "bleeding-hollow" },
  { label: "Chillwind Point", value: "chillwind-point" },
  { label: "Crystalpine Stinger", value: "crystalpine-stinger" },
  { label: "Demon Fall Canyon", value: "demon-fall-canyon" },
  { label: "Dragonmaw", value: "dragonmaw" },
  { label: "Frostmane", value: "frostmane" },
  { label: "Hellscream", value: "hellscream" },
  { label: "Icecrown", value: "icecrown" },
  { label: "Krol Blade", value: "krol-blade" },
  { label: "Light's Hope", value: "lights-hope" },
  { label: "Menethil", value: "menethil" },
  { label: "Nightsong", value: "nightsong" },
  { label: "Old Blanchy", value: "old-blanchy" },
  { label: "Order of the Cloud Serpent", value: "order-of-the-cloud-serpent" },
  { label: "Quel'dorei", value: "queldorei" },
  { label: "Shadowmoon", value: "shadowmoon" },
  { label: "Silverwing Hold", value: "silverwing-hold" },
  { label: "Skywall", value: "skywall" },
  { label: "Spirestone", value: "spirestone" },
  { label: "Stormscale", value: "stormscale" },
  { label: "Sundown Marsh", value: "sundown-marsh" },
  { label: "Whisperwind", value: "whisperwind" },
  { label: "World Tree", value: "world-tree" },
  { label: "Wrathbringer", value: "wrathbringer" },
  { label: "Zealot Blade", value: "zealot-blade" }
]
